version: '3'
services:
  db:
    build: dbinit
    container_name: ticket-dockerdb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ticket
    restart: always
    ports:
      - "3306"
  web:
    build: .
    container_name: ticket-dockerwebapp
    restart: always
    ports:
      - "8081:8080"
    depends_on: 
      - db